/* ============================================================
   AI Mock Exam — Question Bank
   Types: mc (single multiple-choice), multi (choose all),
          fill (fill in the blank), match (matching), essay
   Each attempt draws: 2 essays + 4 challenging + 32 standard = 50 pts
   ============================================================ */

const BANK = {

/* ---------- STANDARD POOL (1 pt each) ---------- */
standard: [
 // ---- Module A: AI fundamentals ----
 {t:"mc",topic:"AI",q:"The only type of AI that exists today is:",
  o:["Artificial General Intelligence (Strong AI)","Artificial Narrow Intelligence (Weak AI)","Artificial Super Intelligence","Reinforcement Intelligence"],a:"Artificial Narrow Intelligence (Weak AI)",
  e:"ANI/Weak AI is focused on one narrow task (Siri, translation, self-driving). AGI and ASI are still hypothetical."},
 {t:"mc",topic:"AI",q:"AI, Machine Learning and Deep Learning relate as:",
  o:["Three separate fields","DL ⊂ ML ⊂ AI (nested)","AI ⊂ ML ⊂ DL","ML ⊂ AI ⊂ DL"],a:"DL ⊂ ML ⊂ AI (nested)",
  e:"Like Russian dolls: Deep Learning is a subset of Machine Learning, which is a subset of AI."},
 {t:"mc",topic:"AI",q:"The three driving forces behind the recent AI boom are:",
  o:["Cloud, mobile, IoT","Computing power, data availability, better algorithms","Python, GPUs, the internet","Money, marketing, hype"],a:"Computing power, data availability, better algorithms",
  e:"Plus a fourth: broad investment by large companies."},
 {t:"mc",topic:"AI",q:"Machine Learning differs from classical programming because it:",
  o:["Uses more if-then rules","Learns patterns from data instead of being explicitly programmed","Always uses neural networks","Needs no data"],a:"Learns patterns from data instead of being explicitly programmed",
  e:"ML = data-driven algorithms that learn for themselves."},
 {t:"fill",topic:"AI",q:"Solving a problem by solving smaller occurrences of the same problem is called ______ (one word).",
  accept:["recursion"],e:"Recursion = divide and conquer; defining an operation in terms of itself."},
 {t:"mc",topic:"AI",q:"Every recursive function must have a … that stops it from calling itself forever:",
  o:["loop","base case","queue","heuristic"],a:"base case",
  e:"The base case is a simple case answered directly; the recursive case reduces toward it."},
 {t:"mc",topic:"AI",q:"The classic recursive puzzle of moving disks between three rods is:",
  o:["The Travelling Salesman","The Towers of Hanoi","Sudoku","The region colouring problem"],a:"The Towers of Hanoi",
  e:"Move n-1 to auxiliary, move 1 to destination, move n-1 from auxiliary to destination."},
 {t:"mc",topic:"AI",q:"Crafting clear, context-rich prompts to get good output from generative AI is called:",
  o:["fine-tuning","prompt engineering","tokenization","backpropagation"],a:"prompt engineering",
  e:"Minimum-effort prompts give low-quality results; you must refine and add context."},

 // ---- Module A: Graph search ----
 {t:"mc",topic:"Graph",q:"DFS uses a … while BFS uses a …:",
  o:["queue / stack","stack / queue","list / matrix","tree / graph"],a:"stack / queue",
  e:"Depth-First uses a stack (recursive/backtracking); Breadth-First uses a queue (level by level)."},
 {t:"mc",topic:"Graph",q:"Dijkstra's algorithm is best described as:",
  o:["an informed search","a greedy shortest-path algorithm","a clustering method","a heuristic estimator"],a:"a greedy shortest-path algorithm",
  e:"It adds cost to edges and always expands the lowest-cost known node (greedy)."},
 {t:"mc",topic:"Graph",q:"A* improves on Dijkstra by adding:",
  o:["edge weights","a heuristic toward the goal","more nodes","backtracking"],a:"a heuristic toward the goal",
  e:"A* = Dijkstra + heuristic cost on each node → smarter sorting toward the goal."},
 {t:"fill",topic:"Graph",q:"A rule-of-thumb function that estimates how close a state is to the goal is a ______ (one word).",
  accept:["heuristic"],e:"A heuristic is a quick, crude hint; it doesn't guarantee the optimal solution."},
 {t:"mc",topic:"Graph",q:"In a graph, the connection between two nodes is called an:",
  o:["edge","leaf","centroid","token"],a:"edge",
  e:"Nodes (vertices) are objects/states; edges are the connections/operations between them."},
 {t:"mc",topic:"Graph",q:"A problem defined by variables, domains and constraints that must all hold is a:",
  o:["regression problem","Constraint Satisfaction Problem (CSP)","clustering problem","greedy search"],a:"Constraint Satisfaction Problem (CSP)",
  e:"Examples: region colouring, Sudoku, cryptarithmetic — solved with backtracking."},
 {t:"mc",topic:"Graph",q:"An adjacency list is an efficient way to represent a … graph:",
  o:["dense","sparse","directed","weighted"],a:"sparse",
  e:"Adjacency list stores each node's neighbours (good for few edges); a matrix is fast for edge lookup."},

 // ---- ML basics ----
 {t:"mc",topic:"ML",q:"In supervised learning, the known output of the training data is called the:",
  o:["feature","label","centroid","token"],a:"label",
  e:"Features (X) are inputs; the label (y) is the output to predict."},
 {t:"mc",topic:"ML",q:"Grouping customers by purchasing behaviour (no labels) is:",
  o:["classification","regression","clustering (unsupervised)","reinforcement learning"],a:"clustering (unsupervised)",
  e:"No labels → unsupervised; grouping similar points → clustering."},
 {t:"mc",topic:"ML",q:"Predicting a house price is a … problem:",
  o:["classification","regression","clustering","association"],a:"regression",
  e:"Continuous numeric output → regression. Categorical output → classification."},
 {t:"mc",topic:"ML",q:"Learning by trial-and-error with rewards in an environment is:",
  o:["supervised learning","unsupervised learning","reinforcement learning","transfer learning"],a:"reinforcement learning",
  e:"An agent interacts with an environment and learns from rewards."},
 {t:"fill",topic:"ML",q:"A model that memorises the training data and performs poorly on new data is said to be ______.",
  accept:["overfitting","overfitted","overfit"],e:"Overfitting = too specific. Underfitting = too simple. Goal = good generalization."},
 {t:"mc",topic:"ML",q:"The generalisation of a line to higher dimensions (a decision boundary) is a:",
  o:["centroid","hyperplane","feature map","lemma"],a:"hyperplane",
  e:"Classification finds decision-boundary hyperplanes; regression fits a function hyperplane."},
 {t:"mc",topic:"ML",q:"Values you choose (not learned), like tree depth or learning rate, are:",
  o:["parameters","hyper-parameters","labels","residuals"],a:"hyper-parameters",
  e:"Parameters are learned from data (weights, slope); hyper-parameters are chosen settings."},
 {t:"mc",topic:"ML",q:"For an iterative learner, the data split used during training to check fit (without touching the test set) is the:",
  o:["training set","validation set","test set","bootstrap set"],a:"validation set",
  e:"Train to fit, validate during training, test once at the very end."},

 // ---- Decision trees & random forest ----
 {t:"mc",topic:"Trees",q:"A decision tree stops splitting at a:",
  o:["root node","leaf node","decision node","centroid"],a:"leaf node",
  e:"A leaf is a pure (unmixed) subset = a final prediction."},
 {t:"mc",topic:"Trees",q:"Which measures the impurity / chaos of a dataset?",
  o:["R²","Entropy","RMSE","Cosine similarity"],a:"Entropy",
  e:"Entropy and Gini impurity both measure impurity (0 = pure)."},
 {t:"mc",topic:"Trees",q:"A decision tree chooses the split with the highest:",
  o:["entropy","information gain","learning rate","bias"],a:"information gain",
  e:"Information gain = the biggest reduction in impurity (most order created)."},
 {t:"fill",topic:"Trees",q:"Cutting back tree branches (or limiting depth) to reduce overfitting is called ______.",
  accept:["pruning","prune"],e:"Pruning / max depth helps a tree generalise better."},
 {t:"mc",topic:"Trees",q:"A random forest combines its trees by:",
  o:["averaging weights","majority vote","backpropagation","pruning"],a:"majority vote",
  e:"Ensemble of many trees voting = wisdom of crowds; resists overfitting."},
 {t:"mc",topic:"Trees",q:"Randomly sampling the dataset (with replacement) for each tree is called:",
  o:["feature bagging","bootstrapping","aggregation","dropout"],a:"bootstrapping",
  e:"Bootstrapping (data bagging) + feature bagging create varied trees."},
 {t:"mc",topic:"Trees",q:"Encoding {sunny, overcast, rain} as {1,2,3} is risky because it:",
  o:["uses too much memory","implies a false order/magnitude","cannot be computed","is one-hot encoding"],a:"implies a false order/magnitude",
  e:"Label/ordinal encoding implies sunny<overcast<rain; use one-hot encoding instead."},
 {t:"mc",topic:"Trees",q:"A nuanced view of classifier performance beyond accuracy is given by a:",
  o:["confusion matrix","scatter plot","histogram","dendrogram"],a:"confusion matrix",
  e:"A confusion matrix compares true vs predicted labels."},

 // ---- Linear regression ----
 {t:"mc",topic:"Regression",q:"Linear regression fits the line by minimising the:",
  o:["information gain","squared residuals (least squares)","entropy","cosine distance"],a:"squared residuals (least squares)",
  e:"Residuals = distances between actual points and the line; minimise their squares (SSR/OLS)."},
 {t:"fill",topic:"Regression",q:"The metric measuring how well a regression model explains the variance, where 1 = perfect fit, is ______ (symbol).",
  accept:["r2","r 2","r squared","rsquared","r²"],e:"R² (coefficient of determination), in %, used to compare models."},
 {t:"mc",topic:"Regression",q:"In f(x) = b + m·x, the value m is the:",
  o:["intercept","slope","residual","bias"],a:"slope",
  e:"m = slope (steepness); b = intercept (where the line crosses the y-axis)."},
 {t:"mc",topic:"Regression",q:"Using one input feature is simple linear regression; using several features is:",
  o:["polynomial regression","multiple linear regression","logistic regression","k-means"],a:"multiple linear regression",
  e:"Several features → a plane/hyperplane: y = b + m1x1 + m2x2 + …"},

 // ---- Unsupervised & recommenders ----
 {t:"mc",topic:"Unsupervised",q:"k-Means is a … algorithm:",
  o:["supervised classification","unsupervised clustering","regression","reinforcement"],a:"unsupervised clustering",
  e:"It partitions data into k clusters around centroids."},
 {t:"mc",topic:"Unsupervised",q:"The method to choose the optimal number of clusters k is the:",
  o:["elbow method","confusion matrix","bagging","softmax"],a:"elbow method",
  e:"The elbow method picks k where adding clusters stops helping much."},
 {t:"mc",topic:"Recommenders",q:"A recommender that suggests trending/most-liked items to everyone is:",
  o:["content-based","popularity-based","collaborative filtering","user-based"],a:"popularity-based",
  e:"Often uses a weighted rating (average score + number of votes), e.g. the IMDb formula."},
 {t:"mc",topic:"Recommenders",q:"Collaborative filtering bases recommendations on:",
  o:["item features (genre, cast)","other users' behaviour/network","popularity only","word embeddings"],a:"other users' behaviour/network",
  e:'"Mapping of the network" — vs content-based "mapping of the features".'},
 {t:"fill",topic:"Recommenders",q:"The collaborative-filtering problem of not being able to recommend for a brand-new user or item is called the ______ ______ problem.",
  accept:["cold start"],e:"Other CF problems: data sparsity and scalability."},
 {t:"mc",topic:"Recommenders",q:"Content-based recommenders compare item vectors using:",
  o:["Euclidean weights","cosine similarity","information gain","RMSE"],a:"cosine similarity",
  e:"Cosine similarity measures the angle between two feature vectors."},

 // ---- Neural networks ----
 {t:"mc",topic:"NeuralNets",q:"A neuron's output value (0–1) is called its:",
  o:["weight","activation","bias","epoch"],a:"activation",
  e:"It is the activation function applied to the weighted sum + bias."},
 {t:"mc",topic:"NeuralNets",q:"Which activation is used ONLY in the output layer to give probabilities that sum to 1?",
  o:["ReLU","sigmoid","softmax","tanh"],a:"softmax",
  e:"Softmax links output neurons into one group and picks a clear winner."},
 {t:"mc",topic:"NeuralNets",q:"One full pass of all training data through the network is an:",
  o:["epoch","iteration","batch","encoding"],a:"epoch",
  e:"Batch size = samples before one weight update; epoch = one full pass."},
 {t:"mc",topic:"NeuralNets",q:"Working backward layer by layer to compute weight updates is:",
  o:["forward pass","backpropagation","pooling","tokenization"],a:"backpropagation",
  e:"Backpropagation is the recursive, efficient method for the updates."},
 {t:"mc",topic:"NeuralNets",q:"The parameter controlling how big each weight-update step is:",
  o:["batch size","learning rate","epoch","dropout rate"],a:"learning rate",
  e:"Too big overshoots the optimum; too small trains very slowly."},
 {t:"fill",topic:"NeuralNets",q:"The regularization technique that randomly disables neurons during training to fight overfitting is ______.",
  accept:["dropout"],e:"Dropout forces the network to learn robust, generalizable features."},
 {t:"mc",topic:"NeuralNets",q:"Keras is best described as:",
  o:["a GPU","the high-level API of TensorFlow","a dataset","an optimizer"],a:"the high-level API of TensorFlow",
  e:"Keras makes TensorFlow easy; we use it in this course."},
 {t:"mc",topic:"NeuralNets",q:"Scaling pixel values by dividing by 255 to get a [0,1] range is:",
  o:["augmentation","normalization","pooling","encoding"],a:"normalization",
  e:"All data (train/test/new) must be preprocessed the same way."},
 {t:"mc",topic:"NeuralNets",q:"When two models perform equally, preferring the simpler one is:",
  o:["the bias-variance tradeoff","Occam's Razor","the elbow method","gradient descent"],a:"Occam's Razor",
  e:"The simpler model usually generalises better."},

 // ---- Computer vision / CNN ----
 {t:"mc",topic:"CNN",q:"A convolution slides a filter over an image to produce a:",
  o:["centroid","feature map","token","lemma"],a:"feature map",
  e:"Each filter (kernel) produces one feature map = one new dimension highlighting a feature."},
 {t:"mc",topic:"CNN",q:'Padding that keeps the output the same size as the input is called:',
  o:["valid","same","stride","pool"],a:"same",
  e:'"valid" = no padding (output shrinks); "same" = pad so output size equals input.'},
 {t:"mc",topic:"CNN",q:"Max pooling reduces the … of a feature map:",
  o:["depth","size/resolution","number of classes","learning rate"],a:"size/resolution",
  e:"Pooling shrinks size (not depth) → fewer parameters, looks at larger areas."},
 {t:"mc",topic:"CNN",q:"Detecting WHERE a face is (not whose) is:",
  o:["face recognition","face detection","segmentation","NER"],a:"face detection",
  e:"Detection needs no neural net (Haar cascade works); recognition needs one."},
 {t:"fill",topic:"CNN",q:"Creating new training images by rotating, zooming and flipping existing ones is called data ______.",
  accept:["augmentation"],e:"Data augmentation enlarges the dataset & prevents overfitting; only during training."},
 {t:"mc",topic:"CNN",q:"A faster alternative to a Flatten layer that averages each feature map to one number is:",
  o:["Max Pooling","Global Average Pooling (GAP)","Dropout","Batch Normalization"],a:"Global Average Pooling (GAP)",
  e:"GAP is simpler/faster than Flatten when the network is deep enough."},
 {t:"mc",topic:"CNN",q:"The classical (non-neural) face-detection algorithm using a cascade of pattern tests is:",
  o:["ResNet","Viola-Jones / Haar cascade","Word2Vec","k-Means"],a:"Viola-Jones / Haar cascade",
  e:"It breaks detection into quick staged tests (a cascade), so it runs in real time."},

 // ---- Transfer learning ----
 {t:"mc",topic:"Transfer",q:"Transfer learning reuses a … model on a related task:",
  o:["random","pre-trained","linear","unsupervised"],a:"pre-trained",
  e:'"Standing on the shoulders of giants" — reuse features learned on a large dataset.'},
 {t:"mc",topic:"Transfer",q:"Keeping the pre-trained body frozen and training only a new head is:",
  o:["fine-tuning","feature extraction","bagging","dropout"],a:"feature extraction",
  e:"Fine-tuning instead unfreezes layers and trains them with a very small learning rate."},
 {t:"fill",topic:"Transfer",q:"The large image database (1.2M images, 1000 classes) and its challenge that drove CNN innovation is ______.",
  accept:["imagenet","image net"],e:"ImageNet; its ILSVRC challenge. Around 2015 ResNet surpassed humans."},

 // ---- NLP ----
 {t:"mc",topic:"NLP",q:"Splitting text into words/sentences (tokens) is:",
  o:["lemmatization","tokenization","vectorization","stemming"],a:"tokenization",
  e:"Tokenization is the critical first step in the NLP pipeline."},
 {t:"mc",topic:"NLP",q:"Reducing words to a real dictionary base form (using vocabulary) is:",
  o:["stemming","lemmatization","tokenization","padding"],a:"lemmatization",
  e:"Stemming crudely chops endings (may not be a real word); lemmatization gives a real lemma."},
 {t:"fill",topic:"NLP",q:"Common low-meaning words like 'the', 'is', 'and' that are removed as noise are called ______ ______.",
  accept:["stop words","stopwords"],e:"Removing stop words reduces noise before analysis."},
 {t:"mc",topic:"NLP",q:"Identifying people, places, organisations and dates in text is:",
  o:["POS tagging","Named Entity Recognition (NER)","stemming","tokenization"],a:"Named Entity Recognition (NER)",
  e:"NER extracts structured information from unstructured text."},
 {t:"mc",topic:"NLP",q:"Word2Vec and GloVe are examples of:",
  o:["stemmers","pre-trained word embeddings","optimizers","pooling layers"],a:"pre-trained word embeddings",
  e:"Dense embeddings capture semantic relationships; similar words cluster."},
 {t:"mc",topic:"NLP",q:"Bag of Words / CountVectorizer produces vectors that are:",
  o:["dense and small","high-dimensional and sparse","context-aware","already normalized"],a:"high-dimensional and sparse",
  e:"That's why dense embeddings (Word2Vec) or dimensionality reduction are preferred."},
],

/* ---------- CHALLENGING POOL (2 pts each) ---------- */
challenging: [
 {t:"mc",topic:"ML",q:"A model scores 99% on training data but 71% on test data. What is happening, and which is a valid fix for a NEURAL NETWORK?",
  o:["Underfitting — add more layers","Overfitting — add dropout / data augmentation","Underfitting — lower the learning rate","Overfitting — remove the validation set"],a:"Overfitting — add dropout / data augmentation",
  e:"Big train-test gap = overfitting. NN fixes: dropout, data augmentation, simpler model, early stopping. (For a tree: pruning / max depth.)"},
 {t:"mc",topic:"Graph",q:"You need the shortest route on a weighted map and you have GPS coordinates. Best choice and why?",
  o:["BFS — it explores level by level","Dijkstra — but A* with a straight-line (Euclidean) heuristic is faster","DFS — it backtracks efficiently","k-Means — it clusters the nodes"],a:"Dijkstra — but A* with a straight-line (Euclidean) heuristic is faster",
  e:"Dijkstra finds shortest paths; A* adds a heuristic (Euclidean/Manhattan distance) to steer toward the goal faster."},
 {t:"mc",topic:"CNN",q:"A 5×5 image is convolved with a 3×3 filter using 'valid' padding. What is the output size, and what keeps it 5×5?",
  o:["7×7; 'valid' keeps it","3×3; 'same' padding keeps it 5×5","5×5; no padding needed","2×2; stride keeps it 5×5"],a:"3×3; 'same' padding keeps it 5×5",
  e:"valid: 5−3+1 = 3×3. Use 'same' padding to keep output equal to input size."},
 {t:"match",topic:"NeuralNets",q:"Match each activation function to where/why it is used:",
  left:["Sigmoid","ReLU","Softmax"],
  right:["Hidden layers; newer, fixes some sigmoid drawbacks","Output layer only; probabilities that sum to 1, clear winner","Hidden or single output; S-shape squish to [0,1], older"],
  correct:{"Sigmoid":"Hidden or single output; S-shape squish to [0,1], older","ReLU":"Hidden layers; newer, fixes some sigmoid drawbacks","Softmax":"Output layer only; probabilities that sum to 1, clear winner"},
  e:"Sigmoid: hidden/single output. ReLU: hidden layers. Softmax: output layer, sums to 1."},
 {t:"match",topic:"Graph",q:"Match each search algorithm to its description:",
  left:["DFS","BFS","Dijkstra","A*"],
  right:["Level-by-level using a queue","Informed = Dijkstra + heuristic","Depth-first using a stack / backtracking","Greedy shortest-path using edge costs"],
  correct:{"DFS":"Depth-first using a stack / backtracking","BFS":"Level-by-level using a queue","Dijkstra":"Greedy shortest-path using edge costs","A*":"Informed = Dijkstra + heuristic"},
  e:"DFS=stack/backtrack, BFS=queue, Dijkstra=greedy shortest path, A*=Dijkstra+heuristic."},
 {t:"mc",topic:"Trees",q:"Why does a random forest generalise better than a single decision tree?",
  o:["It uses entropy instead of Gini","It averages many varied trees (bagging + feature bagging), cancelling individual biases","It always prunes to depth 1","It is an iterative learner"],a:"It averages many varied trees (bagging + feature bagging), cancelling individual biases",
  e:"A single tree overfits; the ensemble's majority vote over varied trees smooths this out."},
 {t:"match",topic:"NLP",q:"Match each NLP term to its meaning:",
  left:["Tokenization","Lemmatization","NER","Stop words"],
  right:["Common low-meaning words removed as noise","Splitting text into tokens","Find/classify entities (people, places, dates)","Reduce a word to its dictionary base form"],
  correct:{"Tokenization":"Splitting text into tokens","Lemmatization":"Reduce a word to its dictionary base form","NER":"Find/classify entities (people, places, dates)","Stop words":"Common low-meaning words removed as noise"},
  e:"Tokenize→split; lemmatize→base form; NER→entities; stop words→noise removed."},
 {t:"mc",topic:"Transfer",q:"You have only 500 labelled images but need a high-accuracy classifier fast. Best strategy?",
  o:["Train a deep CNN from scratch for many epochs","Use transfer learning: freeze a pre-trained body (feature extraction), add a head, plus data augmentation","Use k-Means clustering","Use linear regression on the pixels"],a:"Use transfer learning: freeze a pre-trained body (feature extraction), add a head, plus data augmentation",
  e:"Transfer learning needs little data and trains fast; augmentation enlarges the tiny set."},
 {t:"fill",topic:"NeuralNets",q:"Name the optimisation algorithm that follows the gradient of the loss downhill to minimise error (two words).",
  accept:["gradient descent"],e:"Gradient descent; the learning rate sets the step size, Adam is a good optimizer."},
 {t:"mc",topic:"CNN",q:"In a CNN, what determines the DEPTH of the output volume after a convolution layer?",
  o:["The image height","The number of filters used","The stride","The pooling size"],a:"The number of filters used",
  e:"Each filter adds one feature map (one layer); filter size affects height/width, stride/padding affect size."},
],

/* ---------- ESSAY POOL (5 pts each) ---------- */
essay: [
 {topic:"DL",q:"Explain the difference between Machine Learning and Deep Learning, and situate both within AI. Cover feature handling, data/compute needs, and give one example of each.",
  keywords:["subset","neural network","hidden layer","features","raw","data","gpu","compute","label","cnn","decision tree","brain"],
  model:"AI ⊃ ML ⊃ DL (nested dolls). AI = making machines do tasks needing human intelligence. ML = a subset of AI that learns patterns from data instead of explicit programming. DL = a subset of ML using brain-inspired neural networks with many hidden layers. Key difference: in ML you engineer/select features yourself; in DL you feed raw input and the network extracts features itself. DL therefore needs much more labelled data + compute (GPUs) and time, which is why it boomed only recently. Example ML: decision tree/random forest on engineered features. Example DL: a CNN classifying cats vs dogs directly from images."},
 {topic:"Trees",q:"Describe how a decision tree is built and explain why a random forest improves on it.",
  keywords:["split","pure","leaf","entropy","gini","information gain","overfit","prune","ensemble","majority vote","bootstrap","feature bagging","wisdom"],
  model:"A decision tree recursively splits data with questions to reach subsets that are as pure as possible; a pure subset is a leaf. The split chosen at each node maximises information gain (largest drop in entropy/Gini impurity). Splitting until pure perfectly fits the training data but overfits → use max depth/pruning. A random forest is an ensemble: many trees made different by bootstrapping (random data samples with replacement) and feature bagging (random feature subset per split), combined by majority vote (wisdom of crowds). Averaging varied trees cancels individual biases, so it generalises better and resists overfitting."},
 {topic:"NeuralNets",q:"Explain how a neural network learns: forward pass, loss, gradient descent, backpropagation, learning rate and epoch.",
  keywords:["forward pass","loss","cost","error","optimizer","gradient descent","backpropagation","weights","bias","learning rate","epoch","validation","overfit"],
  model:"A neuron outputs an activation = activation function (sigmoid/ReLU/softmax) of the weighted sum of inputs + a bias. Learning = finding weights/biases that minimise error. Cycle: (1) forward pass — run a batch, compute the loss/cost (how wrong); (2) an optimizer (Adam) computes how to nudge the last layer's weights; (3) backpropagation works backward layer by layer computing all updates; (4) the learning rate sets step size (too big overshoots, too small is slow). This is gradient descent (follow the loss downhill). One full pass of all data = an epoch; repeat over epochs, watching validation loss to stop before overfitting."},
 {topic:"Recommenders",q:"Compare the three types of recommender systems, giving one strength and one weakness of each.",
  keywords:["popularity","weighted rating","content","user profile","features","cosine","collaborative","network","sparsity","cold start","scalability","personalised"],
  model:"(1) Popularity-based: same trending items for all, via a weighted rating (avg score + #votes). + simple/good for new users; – not personalised. (2) Content-based ('mapping of features'): builds a user profile from ratings + item features (often one-hot), recommends similar items via cosine similarity. + personalised, works without other users; – can't recommend a never-seen genre (no data). (3) Collaborative filtering ('mapping of the network'): uses other users' behaviour (user-based or item-based). + finds surprising cross-genre items; – suffers data sparsity, cold start (new user/item), and scalability."},
 {topic:"CNN",q:"Explain the three steps of a Convolutional Neural Network (convolution, pooling, flatten/full connection) and why CNNs are used for images.",
  keywords:["convolution","filter","kernel","feature map","learn","padding","stride","pooling","max","downsample","flatten","global average pooling","dense","classify","augmentation"],
  model:"A CNN learns its own filters instead of hand-coding them. (1) Convolution: learnable filters/kernels slide over the image producing feature maps; deeper layers detect more complex objects; padding ('same' keeps size) and stride control output. Many filters add depth. (2) Pooling (max/average): downsamples feature-map size (not depth), cutting parameters and looking at larger areas. (3) Flatten & full connection: flatten the feature maps into a 1-D vector (or use Global Average Pooling) feeding a fully-connected Dense classifier. CNNs suit images because they exploit spatial patterns and reuse filters, vastly fewer parameters than a plain network on raw pixels. Data augmentation helps prevent overfitting."},
 {topic:"Transfer",q:"Explain transfer learning: what it is, the two modes (feature extraction and fine-tuning), and why it is useful.",
  keywords:["pre-trained","imagenet","reuse","body","head","freeze","feature extraction","fine-tuning","unfreeze","small learning rate","less data","faster","carbon"],
  model:"Transfer learning reuses a model trained on one task as the starting point for a related task ('shoulders of giants'), because designing/training deep nets from scratch is an art-form, data-hungry and slow. A pre-trained model is trained on a large dataset (e.g. ImageNet). Mode 1 — feature extraction: keep the pre-trained body with frozen weights, remove its head, add a new classifier head, train only that head. Mode 2 — fine-tuning: unfreeze some/all body layers and train with a very small learning rate so features aren't destroyed (best: train frozen first, then unfreeze). Benefits: far less labelled data, much faster training, lower carbon footprint. The new head often uses Global Average Pooling; models come from TensorFlow Hub/Hugging Face (ResNet, EfficientNet)."},
 {topic:"NLP",q:"Walk through the NLP pipeline from raw text to numerical vectors, naming the key preprocessing and vectorization techniques.",
  keywords:["unstructured","tokenization","cleaning","normalization","stop words","stemming","lemmatization","pos","ner","bag of words","countvectorizer","sparse","embeddings","word2vec","glove","cosine","transformer"],
  model:"NLP turns unstructured text into vectors. (1) Tokenization: split text into tokens (words). (2) Preprocessing: text cleaning (remove punctuation/HTML), normalization (lowercase, remove accents), remove stop words, and reduce to base form via stemming (crude chop, may not be real word) or lemmatization (dictionary lemma, real word). Optional enrichment: POS tagging (grammar role, needs a language model) and NER (entities). (3) Vectorization: Bag of Words/CountVectorizer is context-independent (one-hot based) but gives high-dimensional sparse vectors; better are pre-trained dense embeddings (Word2Vec, GloVe) capturing semantics (similar words cluster). Context-aware vectorization needs a (large) language model using the context window; SOTA uses transformers (attention) via Hugging Face. A common application is sentiment analysis."},
]
};

/* ============================================================
   QUIZZES — several mock exams. Each draws fresh questions from
   BANK every attempt, so the "same" quiz is different each time.
   topics (optional) filters the pools to those question.topic tags.
   target is computed as 80% of the actual total.
   ============================================================ */
const TOPIC_GROUPS = {
  ML: ["ML","Trees","Regression","Unsupervised","Recommenders"],
  DL: ["DL","NeuralNets","CNN","Transfer","NLP"],
  FUND: ["AI","Graph"]
};
const QUIZZES = [
  { id:"full",   title:"AI Mock Exam — Full (real format)",
    compose:{standard:32,challenging:4,essay:2},
    blurb:"2 essays + 4 challenging + 32 standard = 50 pts. Mirrors your real Canvas exam exactly." },
  { id:"noessay",title:"AI Mock — Auto-graded 40",
    compose:{standard:32,challenging:4,essay:0},
    blurb:"Same MC / fill-in / matching mix but no essays — instant, fully automatic grading." },
  { id:"quick",  title:"AI Mock — Quickfire 20",
    compose:{standard:20,challenging:0,essay:0},
    blurb:"A fast 20-question recall round across the whole course." },
  { id:"ml",     title:"AI Mock — Machine Learning focus",
    topics:TOPIC_GROUPS.ML, compose:{standard:20,challenging:2,essay:1},
    blurb:"ML half only: trees & random forest, regression, k-means, recommenders." },
  { id:"dl",     title:"AI Mock — Deep Learning focus",
    topics:TOPIC_GROUPS.DL, compose:{standard:18,challenging:2,essay:1},
    blurb:"DL half only: neural networks, CNNs, transfer learning, NLP." },
  { id:"fund",   title:"AI Mock — Fundamentals (AI & Graphs)",
    topics:TOPIC_GROUPS.FUND, compose:{standard:12,challenging:1,essay:0},
    blurb:"History, recursion, graph search (DFS/BFS/Dijkstra/A*) & constraint problems." },
];
